name:                dictionary-compression
version:             0.1.0.0
github:              "kmein/dictionary-compression"
license:             BSD3
author:              "Kierán Meinhardt"
maintainer:          "kieran.meinhardt@gmail.com"
copyright:           "Copyright: (c) 2017 Kierán Meinhardt"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  dictionary-compression-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dictionary-compression

tests:
  dictionary-compression-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dictionary-compression
    - doctest
