name: prim
version: 0.0.1
synopsis: Algorithms and data structures coding challenge
description: See README at <https://github.com/kmein/challenges/prim/README.md>
maintainer: Kierán Meinhardt <kieran.meinhardt@gmail.com>
license: MIT
github: kmein/challenges
category: Data

ghc-options: -O3 -Wall

dependencies:
    - base >= 4.9 && < 5
    - mtl
    - primes
    - random
    - vector
    - MemoTrie

executable:
    main: prim.hs
    source-dirs: .
