name: prim
version: 0.0.1
synopsis: Algorithms and data structures coding challenge
description: See README at <https://github.com/kmein/challenges/prim/README.md>
maintainer: Kierán Meinhardt <kieran.meinhardt@gmail.com>
license: MIT
github: kmein/challenges
category: Data

ghc-options: -O2 -Wall

default-extensions:
    - FlexibleContexts

dependencies:
    - base >= 4.9 && < 5
    - mtl
    - primes
    - random
    - vector
    - MemoTrie

library:
    source-dirs:
        - .
    exposed-modules:
        - Prim

executable:
    source-dirs:
        - .
    main: Main.hs
    dependencies:
        - prim

tests:
    spec:
        cpp-options: -DTEST
        main: Test.hs
        source-dirs: test
        dependencies:
            - prim
            - vector
            - tasty
            - tasty-hunit
            - tasty-quickcheck
